name: python

on:
  pull_request:
    paths:
      - "python/**"
      - .github/workflows/python.yaml
      - WORKSPACE
  push:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cache
        id: bazel-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-bazel-cache-python
      - run: |
          bazel run //python:main
